### ISSUE TITLE
Remove Warpers

### ISSUE THREAD

**Issue by Kolipolu** [DDE-64-bit/No-Leviathans#1]
Hi,

I try to remove Warpers, but each time I try the code I added I still get the Warpers balls to spawn infinitly and it makes my game lag as hell. It looks like the Warper's spawner try to make them spawn, but are not able too so they keep staying in an infinite loop. Do you know what to add to make them not to spawn at all. Here's what I added in the condition you showed in your tuto.

if (name == "ReaperLeviathan" || name == "GhostLeviathan" || name == "Warper" || name == "WarperSpawner" || name == "WarpBall")

**Comment by DDE-64-bit** [comment]
Hi, 

If you replace "UnityEngine.Object.Destroy(base.gameObject);" with "base.gameObject.SetActive(false);" it should remove the balls. 

Here is a [link](https://www.nexusmods.com/subnautica/mods/1722?tab=posts#:~:text=Not%20an%20issue,glitching%20the%20game.).

**Comment by Kolipolu** [comment]
Nice! Thank you for the quick solution! :)
